rules:
  color-named: never
  color-no-hex: true
  property-layout-mappings:
    - flow-relative
    - ignoreProperties:
        - overflow-x
        - overflow-y
  unit-layout-mappings:
    - flow-relative
  value-keyword-layout-mappings:
    - flow-relative
    - ignoreProperties:
        - caption-side
languageOptions:
  directionality:
    block: top-to-bottom
    inline: left-to-right
extends:
  - '@siemens/stylelint-config-scss/stylelintrc.yml'
ignoreFiles:
  - dist/**
  - projects/**/dist/*.scss
