/* eslint-disable */

// Auto-generated file. Run 'yarn update-translatable-keys' to update.

export interface SiTranslatableKeys {
  'SI_ALERT_DIALOG.OK'?: string;
  'SI_APPLICATION_HEADER.LAUNCHPAD'?: string;
  'SI_APPLICATION_HEADER.TOGGLE_ACTIONS'?: string;
  'SI_APPLICATION_HEADER.TOGGLE_NAVIGATION'?: string;
  'SI_CONFIRMATION_DIALOG.NO'?: string;
  'SI_CONFIRMATION_DIALOG.YES'?: string;
  'SI_DELETE_CONFIRMATION_DIALOG.CANCEL_BTN'?: string;
  'SI_DELETE_CONFIRMATION_DIALOG.DELETE_BTN'?: string;
  'SI_DELETE_CONFIRMATION_DIALOG.MESSAGE'?: string;
  'SI_EDIT_DISCARD_DIALOG.CANCEL_BTN'?: string;
  'SI_EDIT_DISCARD_DIALOG.DISABLE_SAVE_DISCARD_BTN'?: string;
  'SI_EDIT_DISCARD_DIALOG.DISABLE_SAVE_MESSAGE'?: string;
  'SI_EDIT_DISCARD_DIALOG.DISCARD_BTN'?: string;
  'SI_EDIT_DISCARD_DIALOG.MESSAGE'?: string;
  'SI_EDIT_DISCARD_DIALOG.SAVE_BTN'?: string;
  'SI_LAUNCHPAD.CLOSE'?: string;
  'SI_LAUNCHPAD.DEFAULT_CATEGORY_TITLE'?: string;
  'SI_LAUNCHPAD.FAVORITE_APPS'?: string;
  'SI_LAUNCHPAD.SHOW_LESS'?: string;
  'SI_LAUNCHPAD.SHOW_MORE'?: string;
  'SI_LAUNCHPAD.SUBTITLE'?: string;
  'SI_LAUNCHPAD.SUB_TITLE'?: string;
  'SI_LAUNCHPAD.TITLE'?: string;
  'SI_LOADING_SPINNER.LABEL'?: string;
  'SI_NAVBAR.OPEN_LAUNCHPAD'?: string;
  'SI_NAVBAR.TOGGLE_NAVIGATION'?: string;
  'SI_PAGINATION.BACK'?: string;
  'SI_PAGINATION.FORWARD'?: string;
  'SI_PAGINATION.NAV_LABEL'?: string;
  'SI_PASSWORD_TOGGLE.HIDE'?: string;
  'SI_PASSWORD_TOGGLE.SHOW'?: string;
}
