/* eslint-disable */

// Auto-generated file. Run 'yarn update-translatable-keys' to update.

export interface SiTranslatableKeys {
  'DASHBOARD.ADD_WIDGET'?: string;
  'DASHBOARD.CANCEL'?: string;
  'DASHBOARD.EDIT'?: string;
  'DASHBOARD.REMOVE_WIDGET_CONFIRMATION_DIALOG.CANCEL'?: string;
  'DASHBOARD.REMOVE_WIDGET_CONFIRMATION_DIALOG.HEADING'?: string;
  'DASHBOARD.REMOVE_WIDGET_CONFIRMATION_DIALOG.MESSAGE'?: string;
  'DASHBOARD.REMOVE_WIDGET_CONFIRMATION_DIALOG.REMOVE'?: string;
  'DASHBOARD.SAVE'?: string;
  'DASHBOARD.WIDGET.EDIT'?: string;
  'DASHBOARD.WIDGET.EXPAND'?: string;
  'DASHBOARD.WIDGET.REMOVE'?: string;
  'DASHBOARD.WIDGET.RESTORE'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.CANCEL'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.DISCARD_CONFIG_CHANGE_DIALOG.CANCEL'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.DISCARD_CONFIG_CHANGE_DIALOG.DISCARD'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.DISCARD_CONFIG_CHANGE_DIALOG.HEADING'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.DISCARD_CONFIG_CHANGE_DIALOG.MESSAGE'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.DISCARD_CONFIG_CHANGE_DIALOG.SAVE'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.NEXT'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.PREVIOUS'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.SAVE'?: string;
  'DASHBOARD.WIDGET_EDITOR_DIALOG.TITLE'?: string;
  'DASHBOARD.WIDGET_LIBRARY.ADD'?: string;
  'DASHBOARD.WIDGET_LIBRARY.CANCEL'?: string;
  'DASHBOARD.WIDGET_LIBRARY.DISCARD_CONFIG_CHANGE_DIALOG.CANCEL'?: string;
  'DASHBOARD.WIDGET_LIBRARY.DISCARD_CONFIG_CHANGE_DIALOG.DISCARD'?: string;
  'DASHBOARD.WIDGET_LIBRARY.DISCARD_CONFIG_CHANGE_DIALOG.HEADING'?: string;
  'DASHBOARD.WIDGET_LIBRARY.DISCARD_CONFIG_CHANGE_DIALOG.MESSAGE'?: string;
  'DASHBOARD.WIDGET_LIBRARY.EMPTY'?: string;
  'DASHBOARD.WIDGET_LIBRARY.NEXT'?: string;
  'DASHBOARD.WIDGET_LIBRARY.PREVIOUS'?: string;
  'DASHBOARD.WIDGET_LIBRARY.SEARCH_PLACEHOLDER'?: string;
  'DASHBOARD.WIDGET_LIBRARY.TITLE'?: string;
}
