name: Next Release
on:
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    secrets:
      SIEMENS_NPM_TOKEN: ${{ secrets.SIEMENS_NPM_TOKEN }}
      SIEMENS_NPM_USER: ${{ secrets.SIEMENS_NPM_USER }}

  publish:
    runs-on: ubuntu-24.04
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # semantic-release needs this
          token: ${{ secrets.ELEMENT_BOT_GITHUB_TOKEN }} # Otherwise, branch protection rules are not bypassed.
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: 'npm'
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - run: npm ci --prefer-offline --no-audit
      - run: npx semantic-release -e ./.releaserc-next.js
        env:
          GIT_AUTHOR_NAME: 'Siemens Element Bot'
          GIT_AUTHOR_EMAIL: 'simpl.si@siemens.com'
          GIT_COMMITTER_NAME: 'Siemens Element Bot'
          GIT_COMMITTER_EMAIL: 'simpl.si@siemens.com'
          GITHUB_TOKEN: ${{ secrets.ELEMENT_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
