name: Release
on:
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    secrets:
      SIEMENS_NPM_TOKEN: ${{ secrets.SIEMENS_NPM_TOKEN }}
      SIEMENS_NPM_USER: ${{ secrets.SIEMENS_NPM_USER }}

  publish:
    runs-on: ubuntu-22.04
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # semantic-release needs this
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: 'npm'
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - run: npm ci --prefer-offline --no-audit
      - run: npx semantic-release
        env:
          GIT_AUTHOR_NAME: 'Siemens Element bot'
          GIT_AUTHOR_EMAIL: 'simpl.si@siemens.com'
          GIT_COMMITTER_NAME: 'Siemens Element bot'
          GIT_COMMITTER_EMAIL: 'simpl.si@siemens.com'
          GH_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN_GH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
