- banner:
  - link "Siemens logo":
    - /url: "#/"
  - heading "My application" [level=1]
  - navigation "Main navigation":
    - link "Module 1":
      - /url: "#/viewer/viewer/m1"
    - button "Module 2"
  - button "Tenant 2"
  - button "Notifications" [expanded]
  - dialog "Notifications":
    - button "Message 1"
    - button "Message 2"
  - button /\+\d+ Support/
  - button "Settings"
  - button "Lars Vegas": LV